// automatically generated by the FlatBuffers compiler, do not modify

package app;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class LayerMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_2_0_0(); }
  public static LayerMessage getRootAsLayerMessage(ByteBuffer _bb) { return getRootAsLayerMessage(_bb, new LayerMessage()); }
  public static LayerMessage getRootAsLayerMessage(ByteBuffer _bb, LayerMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public LayerMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String layer() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer layerAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer layerInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int imageId() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createLayerMessage(FlatBufferBuilder builder,
      int layerOffset,
      int imageId) {
    builder.startTable(2);
    LayerMessage.addImageId(builder, imageId);
    LayerMessage.addLayer(builder, layerOffset);
    return LayerMessage.endLayerMessage(builder);
  }

  public static void startLayerMessage(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addLayer(FlatBufferBuilder builder, int layerOffset) { builder.addOffset(0, layerOffset, 0); }
  public static void addImageId(FlatBufferBuilder builder, int imageId) { builder.addInt(1, imageId, 0); }
  public static int endLayerMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishLayerMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedLayerMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public LayerMessage get(int j) { return get(new LayerMessage(), j); }
    public LayerMessage get(LayerMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

